name: Documentation Related
description: Suggest an improvement or report a bug for this project's Documentation
title: "[Doc][Module Name（模块）] Documentation bug or improvement（标题）"
body:
  - type: markdown
    attributes:
      value: |
        能用英文用英文，觉得描述不清就用中文

  - type: textarea
    attributes:
      label: Description
      description: A short description why your find in our document.（简短的描述一下）


  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?(你愿意提交PR吗？)
      description: >
        This is absolutely not required, but we are happy to guide you in the contribution process
                especially if you already have a good understanding of how to implement the fix.
                （这不是必须的，但是我们很高兴您能够提交PR）
      options:
        - label: Yes I am willing to submit a PR!(是的我愿意)

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: |
        The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it.
      options:
        - label: |
            I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
          required: true

  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
